name: Download and Convert M3U8

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次

jobs:
  download_convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create output directory
        run: mkdir -p output

      - name: Download index.m3u8
        run: |
          curl -o output/index.m3u8 http://4gtv.mumi.rip:9877/index.m3u8

      - name: Convert to index.m3u
        run: |
          grep -v "^#EXT" output/index.m3u8 > output/index.m3u

      - name: Upload converted file
        uses: actions/upload-artifact@v4
        with:
          name: index.m3u
          path: output/index.m3u
