name: Convert m3u8 to txt and Push

on:
  schedule:
    - cron: '0 * * * *'  # 每小时执行一次
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  convert_m3u8:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # 克隆仓库

    - name: Install dependencies
      run: |
        # 安装 curl 等必要工具
        sudo apt-get update
        sudo apt-get install -y curl

    - name: Download index.m3u8
      run: |
        mkdir -p output  # 创建 output 文件夹
        curl -o output/index.m3u8 http://4gtv.mumi.rip:9877/index.m3u8  # 下载 m3u8 文件

    - name: Convert m3u8 to txt and extract info
      run: |
        # 提取每个频道的名称和对应的 m3u8 URL
        awk '/#EXTINF:/ { 
            name = substr($0, index($0,$2));  # 提取频道名称
            getline;  # 读取下一行，即 m3u8 URL
            print name "," $0  # 输出格式化后的频道名称和 URL
        }' output/index.m3u8 > output/index.txt

    - name: Upload converted file
      uses: actions/upload-artifact@v4
      with:
        name: index.m3u
        path: output/index.m3u8  # 上传 output/index.m3u8 文件

    - name: Upload index.txt file
      uses: actions/upload-artifact@v4
      with:
        name: index-txt
        path: output/index.txt  # 上传 output/index.txt 文件

    - name: Commit and push if changed
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add -f output/index.m3u8 output/index.txt  # 将 index.m3u8 和 index.txt 添加到暂存区
        if ! git diff --staged --quiet; then  # 如果文件有变化
          git commit -m "Github Action Auto Updated index.m3u8 and index.txt"
          git push
        fi
