name: Convert m3u8 to txt

on:
  schedule:
    - cron: '0 * * * *'  # 每小时执行一次
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  convert_m3u8:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # 克隆仓库

    - name: Install dependencies
      run: |
        # 安装 curl 等必要工具
        sudo apt-get update
        sudo apt-get install -y curl

    - name: Download index.m3u8
      run: |
        mkdir -p output  # 创建 output 文件夹
        curl -o output/index.m3u8 http://4gtv.mumi.rip:9877/index.m3u8  # 下载 m3u8 文件

    - name: Convert m3u8 to txt and clean up
      run: |
        # 使用 sed 过滤掉注释和无效行，然后格式化输出为 CSV
        sed '/^#/d' output/index.m3u8 | awk -F',' '{print $1 "," $2}' > output/index.txt

    - name: Upload output files
      uses: actions/upload-artifact@v3
      with:
        name: m3u8-output
        path: output/index.txt  # 上传 output/index.txt 文件
